# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
title: ladaguedencre
email: valerarezz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Engineering software and other stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""

# User settings
username: ladaguedencre
user_title: ladaguedencre
email: valerarezz@gmail.com
twitter_username: loremipsum
github_username:  ladaguedencre
discord_invite: cj5rg # Example: Discord server invite gg extension like in 'https://discord.gg/cj5rg'
linkedin_public_url: valerii-riznyk
disqus_username: loremipsum
profile_picture: https://avatars.githubusercontent.com/u/19950079?s=400&u=6ca13708f8e2cc0e258b6524ba2f4d63d2a2f1bc&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: about
      url: /about
      key_trigger: 3
  section_2:
    - title: github
      url: http://www.github.com/ladaguedencre
      new_tab: true
      key_trigger: g
    - title: linkedin
      url: https://www.linkedin.com/in/valerii-riznyk/
      new_tab: true
      key_trigger: l
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: Šrink
    url: https://srink.eknm.in

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']